"""Checked-in tool names matching the current Huawei LTS MCP surface."""

TOOL_NAMES = (
    "ConsumerGroupHeartBeat", "CreateAccessConfig", "CreateAgencyAccess",
    "CreateAomMappingRules", "CreateConsumerGroup", "CreateDashBoard",
    "CreateDashboardGroup", "CreateHostGroup", "CreateKeywordsAlarmRule",
    "CreateLogDumpObs", "CreateLogGroup", "CreateLogStream",
    "CreateLogStreamIndex", "CreateNotificationTemplate", "CreateSearchCriterias",
    "CreateSqlAlarmRule", "CreateStructConfig", "CreateStructTemplate", "CreateTags",
    "CreateTransfer", "Createfavorite", "DeleteAccessConfig", "DeleteActiveAlarms",
    "DeleteAomMappingRules", "DeleteConsumerGroup", "DeleteDashboard", "DeleteHostGroup",
    "DeleteKeywordsAlarmRule", "DeleteLogGroup", "DeleteLogStream",
    "DeleteNotificationTemplate", "DeleteSearchCriterias", "DeleteSqlAlarmRule",
    "DeleteStructTemplate", "DeleteTransfer", "Deletefavorite", "DisableLogCollection",
    "EnableLogCollection", "ListAccessConfig", "ListActiveOrHistoryAlarms",
    "ListBreifStructTemplate", "ListCharts", "ListConsumerGroup", "ListCriterias",
    "ListDetailsConsumerGroup", "ListHistorySql", "ListHost", "ListHostGroup",
    "ListKeywordsAlarmRules", "ListLogContext", "ListLogGroups", "ListLogHistogram",
    "ListLogStream", "ListLogStreams", "ListLogs", "ListNotificationTemplate",
    "ListNotificationTemplates", "ListNotificationTopics", "ListQueryAllSearchCriterias",
    "ListQueryStructuredLogs", "ListSqlAlarmRules", "ListStructTemplate",
    "ListStructuredLogsWithTimeRange", "ListTimeLineTrafficStatistics",
    "ListTopnTrafficStatistics", "ListTransfers", "RegisterDmsKafkaInstance",
    "ShowAdminConfig", "ShowAomMappingRule", "ShowAomMappingRules", "ShowCursorByTime",
    "ShowCursorTime", "ShowLogConvergeConfig", "ShowLogStreamShards",
    "ShowMemberGroupAndStream", "ShowNotificationTemplate", "ShowStructTemplate",
    "UpdateAccessConfig", "UpdateAlarmRuleStatus", "UpdateAomMappingRules",
    "UpdateCheckPoint", "UpdateHostGroup", "UpdateKeywordsAlarmRule",
    "UpdateLogConvergeConfig", "UpdateLogGroup", "UpdateLogStream",
    "UpdateNotificationTemplate", "UpdateSqlAlarmRule", "UpdateStructConfig",
    "UpdateStructTemplate", "UpdateSwitch", "UpdateTransfer",
)
